---
- name: Create iredmail directory
  file:
    path: "{{ VOLUMES_PATH }}"
    state: directory
- name: Untemplatet iredmail-docker.conf
  template:
    src: iredmail-docker.conf.j2
    dest: "{{ VOLUMES_PATH }}/iredmail-docker.conf"
- name: Stop container if exists
  docker_container:
    name: iredmail
    state: absent
    force_kill: true
- name: Remove image
  docker_image:
    state: absent
    name: iredmail/mariadb
    tag: nightly
    force_absent: true
- name: Run iredmail
  docker_container:
    name: iredmail
    image: iredmail/mariadb:nightly
    restart_policy: always
    env_file: "{{ VOLUMES_PATH }}/iredmail-docker.conf"
    hostname: "{{ HOSTNAME }}"
    ports:
      - 880:80
      - 8443:443
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 25:25
      - 465:465
      - 587:587
    volumes:
      - /iredmail/data/backup:/var/vmail/backup
      - /iredmail/data/mailboxes:/var/vmail/vmail1
      - /iredmail/data/mlmmj:/var/vmail/mlmmj
      - /iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive
      - /iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy
      - /iredmail/data/custom:/opt/iredmail/custom
      - /iredmail/data/ssl:/opt/iredmail/ssl
      - /iredmail/data/mysql:/var/lib/mysql
      - /iredmail/data/clamav:/var/lib/clamav
      - /iredmail/data/sa_rules:/var/lib/spamassassin
      - /iredmail/data/postfix_queue:/var/spool/postfix
